import { ServiceCategoryKey, ServiceItem, DTenItem } from '../types';

export const serviceImages = {
  hair: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?q=80&w=900&auto=format&fit=crop',
  hairFemale: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=900&auto=format&fit=crop',
  advancedHair: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?q=80&w=900&auto=format&fit=crop',
  hairColour: 'https://images.unsplash.com/photo-1607779097040-26e80aa78e66?q=80&w=900&auto=format&fit=crop',
  beauty: 'https://images.unsplash.com/photo-1512290900672-1f02307374b7?q=80&w=900&auto=format&fit=crop',
  skin: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=900&auto=format&fit=crop',
  body: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=900&auto=format&fit=crop',
  waxing: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=900&auto=format&fit=crop',
  manicure: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?q=80&w=900&auto=format&fit=crop',
  makeup: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=900&auto=format&fit=crop',
};

export const serviceCategories: {
  key: ServiceCategoryKey;
  label: string;
  sublabel: string;
  previewImage: string;
  startingPrice: string;
  description: string;
}[] = [
  {
    key: 'HAIR',
    label: 'HAIR',
    sublabel: 'Styling, Cuts & Treatments',
    previewImage: serviceImages.hair,
    startingPrice: '₹50',
    description: 'Precision haircuts, bespoke styling, luxury keratin, and advanced hair rejuvenation.',
  },
  {
    key: 'BEAUTY',
    label: 'BEAUTY',
    sublabel: 'Threading & Definition',
    previewImage: serviceImages.beauty,
    startingPrice: '₹60',
    description: 'Delicate eyebrow shaping, facial threading, and facial contour refinement.',
  },
  {
    key: 'SKIN',
    label: 'SKIN',
    sublabel: 'Facials & D-TEN Glow',
    previewImage: serviceImages.skin,
    startingPrice: '₹1,000',
    description: 'Hydra facial, Korean glass facial, O3+, and tailored deep purifying treatments.',
  },
  {
    key: 'BODY',
    label: 'BODY',
    sublabel: 'Spa, Massage & Relaxation',
    previewImage: serviceImages.body,
    startingPrice: '₹400',
    description: 'Full body relaxing massage, body polishing, head massage, and therapeutic hair spas.',
  },
  {
    key: 'WAXING',
    label: 'WAXING',
    sublabel: 'Smooth Skin Care',
    previewImage: serviceImages.waxing,
    startingPrice: '₹60',
    description: 'Hygienic, gentle full-body, arm, and facial waxing services.',
  },
  {
    key: 'MANICURE & PEDICURE',
    label: 'MANICURE & PEDICURE',
    sublabel: 'Nail & Feet Spa',
    previewImage: serviceImages.manicure,
    startingPrice: '₹500*',
    description: 'Aqua spa, Seasoul rituals, lotus treatments, and intensive cuticle care.',
  },
  {
    key: 'MAKEUP',
    label: 'MAKEUP',
    sublabel: 'Bridal & Party Artistry',
    previewImage: serviceImages.makeup,
    startingPrice: '₹800*',
    description: 'Celebrity bridal, HD party makeup, reception glam, and bespoke hair styling.',
  },
];

export const services: ServiceItem[] = [
  // ================= HAIR CARE — MALE =================
  {
    id: 'hm-1',
    category: 'HAIR',
    subcategory: 'Hair Care — Male',
    name: 'Hair Cut',
    price: 250,
    starred: false,
    image: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?q=80&w=800&auto=format&fit=crop',
    description: 'Tailored men haircut with consultation, styling assessment, and precision finish.',
  },
  {
    id: 'hm-2',
    category: 'HAIR',
    subcategory: 'Hair Care — Male',
    name: 'Hair Wash',
    price: 50,
    starred: false,
    image: 'https://images.unsplash.com/photo-1582095133179-bfd08e2fc6b3?q=80&w=800&auto=format&fit=crop',
    description: 'Invigorating hair cleanse with premium salon shampoo and scalp conditioning.',
  },
  {
    id: 'hm-3',
    category: 'HAIR',
    subcategory: 'Hair Care — Male',
    name: 'Child Cut',
    price: 200,
    starred: false,
    image: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?q=80&w=800&auto=format&fit=crop',
    description: 'Gentle, patient haircut for children in a comfortable, friendly setting.',
  },
  {
    id: 'hm-4',
    category: 'HAIR',
    subcategory: 'Hair Care — Male',
    name: 'Shaving',
    price: 100,
    starred: false,
    image: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?q=80&w=800&auto=format&fit=crop',
    description: 'Traditional close shave with hot towel preparation and soothing aftershave balm.',
  },
  {
    id: 'hm-5',
    category: 'HAIR',
    subcategory: 'Hair Care — Male',
    name: 'Beard',
    price: 150,
    starred: false,
    image: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?q=80&w=800&auto=format&fit=crop',
    description: 'Beard trimming, sharp line definition, edge taper, and nourishing beard oil.',
  },
  {
    id: 'hm-6',
    category: 'HAIR',
    subcategory: 'Hair Care — Male',
    name: 'Hair Colour',
    price: 800,
    starred: true,
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?q=80&w=800&auto=format&fit=crop',
    description: 'Rich grey coverage and natural tone application with ammonia-safe formulas.',
  },
  {
    id: 'hm-7',
    category: 'HAIR',
    subcategory: 'Hair Care — Male',
    name: 'Beard Colour',
    price: 400,
    starred: true,
    image: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?q=80&w=800&auto=format&fit=crop',
    description: 'Uniform, skin-safe beard darkening and color matching.',
  },
  {
    id: 'hm-8',
    category: 'HAIR',
    subcategory: 'Hair Care — Male',
    name: 'Hair Straightening',
    price: 2000,
    starred: true,
    image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?q=80&w=800&auto=format&fit=crop',
    description: 'Semi-permanent hair smoothing and straightening designed for men hair structure.',
  },
  {
    id: 'hm-9',
    category: 'HAIR',
    subcategory: 'Hair Care — Male',
    name: 'Keratin',
    price: 1500,
    starred: true,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop',
    description: 'Keratin protein infusion for frizz control, natural shine, and silky texture.',
  },
  {
    id: 'hm-10',
    category: 'HAIR',
    subcategory: 'Hair Care — Male',
    name: 'Styling',
    price: 100,
    starred: false,
    image: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?q=80&w=800&auto=format&fit=crop',
    description: 'Professional blow-dry and sculpting using luxury matte paste or gloss pomade.',
  },

  // ================= HAIR CARE — FEMALE =================
  {
    id: 'hf-1',
    category: 'HAIR',
    subcategory: 'Hair Care — Female',
    name: 'Hair Cut',
    price: 1000,
    starred: false,
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?q=80&w=800&auto=format&fit=crop',
    description: 'Custom female haircut tailored to face structure, hair density, and lifestyle.',
  },
  {
    id: 'hf-2',
    category: 'HAIR',
    subcategory: 'Hair Care — Female',
    name: 'Adv. Hair Cut',
    price: 1200,
    starred: false,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop',
    description: 'Advanced multi-layered, textured, or dimensional precision haircut with styling.',
  },
  {
    id: 'hf-3',
    category: 'HAIR',
    subcategory: 'Hair Care — Female',
    name: 'Baby Hair Cut',
    price: 500,
    starred: false,
    image: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?q=80&w=800&auto=format&fit=crop',
    description: 'Gentle, careful trimming and shaping for toddlers and young girls.',
  },
  {
    id: 'hf-4',
    category: 'HAIR',
    subcategory: 'Hair Care — Female',
    name: 'Mundan',
    price: 400,
    starred: false,
    image: 'https://images.unsplash.com/photo-1517832606589-7629c3397143?q=80&w=800&auto=format&fit=crop',
    description: 'Hygienic, ritual head shaving performed with sterile equipment and utmost care.',
  },
  {
    id: 'hf-5',
    category: 'HAIR',
    subcategory: 'Hair Care — Female',
    name: 'French Cut',
    price: 150,
    starred: false,
    image: 'https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?q=80&w=800&auto=format&fit=crop',
    description: 'Chic French edge refinement and fringe shaping.',
  },
  {
    id: 'hf-6',
    category: 'HAIR',
    subcategory: 'Hair Care — Female',
    name: 'Wash & Blow Dry',
    price: 600,
    starred: false,
    image: 'https://images.unsplash.com/photo-1582095133179-bfd08e2fc6b3?q=80&w=800&auto=format&fit=crop',
    description: 'Detox wash followed by voluminous salon blowout and thermal setting.',
  },
  {
    id: 'hf-7',
    category: 'HAIR',
    subcategory: 'Hair Care — Female',
    name: 'Tong',
    price: 1200,
    starred: false,
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=800&auto=format&fit=crop',
    description: 'Gorgeous tong curls, beach waves, or defined glamorous spirals.',
  },
  {
    id: 'hf-8',
    category: 'HAIR',
    subcategory: 'Hair Care — Female',
    name: 'Eyening',
    price: 1000,
    starred: false,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop',
    description: 'Sleek thermal iron straightening for glassy, mirror-like smoothness.',
  },
  {
    id: 'hf-9',
    category: 'HAIR',
    subcategory: 'Hair Care — Female',
    name: 'Hair Wash',
    price: 300,
    starred: false,
    image: 'https://images.unsplash.com/photo-1582095133179-bfd08e2fc6b3?q=80&w=800&auto=format&fit=crop',
    description: 'Deep cleansing hair wash with revitalizing scalp massage.',
  },
  {
    id: 'hf-10',
    category: 'HAIR',
    subcategory: 'Hair Care — Female',
    name: 'Only Blow Dry',
    price: 400,
    starred: false,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop',
    description: 'Fast drying and root-lift volume blowout.',
  },
  {
    id: 'hf-11',
    category: 'HAIR',
    subcategory: 'Hair Care — Female',
    name: 'Deep Conditioner',
    price: 500,
    starred: false,
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?q=80&w=800&auto=format&fit=crop',
    description: 'Intensive moisture mask to nourish dry ends and restore cuticle hydration.',
  },

  // ================= ADVANCED HAIR CARE =================
  {
    id: 'ah-1',
    category: 'HAIR',
    subcategory: 'Advanced Hair Care',
    name: 'Straightening & Texturing Rebonding',
    price: 6000,
    starred: true,
    image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?q=80&w=800&auto=format&fit=crop',
    description: 'High-performance permanent rebonding with advanced texturizing system for pin-straight hair.',
  },
  {
    id: 'ah-2',
    category: 'HAIR',
    subcategory: 'Advanced Hair Care',
    name: 'Kerasmoothning',
    price: 6500,
    starred: true,
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?q=80&w=800&auto=format&fit=crop',
    description: 'Dual-benefit treatment fusing keratin nourishment with smooth, frizz-free alignment.',
  },
  {
    id: 'ah-3',
    category: 'HAIR',
    subcategory: 'Advanced Hair Care',
    name: 'Smoothning',
    price: 5500,
    starred: true,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop',
    description: 'Long-lasting salon smoothing treatment delivering manageable, glossy natural drape.',
  },
  {
    id: 'ah-4',
    category: 'HAIR',
    subcategory: 'Advanced Hair Care',
    name: 'Keratin',
    price: 5000,
    starred: true,
    image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?q=80&w=800&auto=format&fit=crop',
    description: 'Intensive keratin therapy repairing porous strands and creating liquid silk shine.',
  },
  {
    id: 'ah-5',
    category: 'HAIR',
    subcategory: 'Advanced Hair Care',
    name: 'Straightening',
    price: 5500,
    starred: true,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop',
    description: 'Classic chemical straightening delivering long-wearing uniform sleekness.',
  },
  {
    id: 'ah-6',
    category: 'HAIR',
    subcategory: 'Advanced Hair Care',
    name: 'Botox Treatment',
    price: 5500,
    starred: true,
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?q=80&w=800&auto=format&fit=crop',
    description: 'Anti-aging hair botox deeply filling damaged fibres with amino acids and collagen.',
  },
  {
    id: 'ah-7',
    category: 'HAIR',
    subcategory: 'Advanced Hair Care',
    name: 'Nanoplastia',
    price: 6000,
    starred: true,
    image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?q=80&w=800&auto=format&fit=crop',
    description: 'Formaldehyde-free organic straightening and restorative nanotech treatment.',
  },
  {
    id: 'ah-8',
    category: 'HAIR',
    subcategory: 'Advanced Hair Care',
    name: 'Instant Nanoplastia',
    price: 7500,
    starred: true,
    image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?q=80&w=800&auto=format&fit=crop',
    description: 'Ultra-fast organic nanoplastia treatment delivering instantaneous glassy, mirror straight hair.',
  },

  // ================= HAIR COLOUR =================
  {
    id: 'hc-1',
    category: 'HAIR',
    subcategory: 'Hair Colour',
    name: 'Global Hair Colour',
    price: 5000,
    starred: true,
    image: 'https://images.unsplash.com/photo-1607779097040-26e80aa78e66?q=80&w=800&auto=format&fit=crop',
    description: 'Complete roots-to-ends global color transformation with vibrant multidimensional tones.',
  },
  {
    id: 'hc-2',
    category: 'HAIR',
    subcategory: 'Hair Colour',
    name: 'Global Highlight',
    price: 4500,
    starred: true,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop',
    description: 'Sun-kissed or high-contrast foil highlights placed seamlessly across entire hair.',
  },
  {
    id: 'hc-3',
    category: 'HAIR',
    subcategory: 'Hair Colour',
    name: 'Balayage',
    price: 5000,
    starred: true,
    image: 'https://images.unsplash.com/photo-1607779097040-26e80aa78e66?q=80&w=800&auto=format&fit=crop',
    description: 'Freehand French hand-painted gradient coloring for seamless lived-in luxury highlights.',
  },
  {
    id: 'hc-4',
    category: 'HAIR',
    subcategory: 'Ammonia Free Colour',
    name: 'Root Touch Up',
    price: 1400,
    starred: true,
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?q=80&w=800&auto=format&fit=crop',
    description: 'Gentle ammonia-free root regrowth coverage seamlessly matched with existing shade.',
  },
  {
    id: 'hc-5',
    category: 'HAIR',
    subcategory: 'Ammonia Free Colour',
    name: 'Fashion Hair Colour',
    price: 4500,
    starred: true,
    image: 'https://images.unsplash.com/photo-1607779097040-26e80aa78e66?q=80&w=800&auto=format&fit=crop',
    description: 'Expressive fashion shade pigments with ammonia-free nourishing conditioning base.',
  },

  // ================= BEAUTY CARE — THREADING =================
  {
    id: 'bc-1',
    category: 'BEAUTY',
    subcategory: 'Threading',
    name: 'Full Face Threading',
    price: 270,
    starred: false,
    image: 'https://images.unsplash.com/photo-1512290900672-1f02307374b7?q=80&w=800&auto=format&fit=crop',
    description: 'Complete facial hair removal leaving the complexion exceptionally smooth and clean.',
  },
  {
    id: 'bc-2',
    category: 'BEAUTY',
    subcategory: 'Threading',
    name: 'Eye Brows',
    price: 120,
    starred: false,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop',
    description: 'Precision eyebrow threading and architectural arch shaping.',
  },
  {
    id: 'bc-3',
    category: 'BEAUTY',
    subcategory: 'Threading',
    name: 'Fore Head',
    price: 60,
    starred: false,
    image: 'https://images.unsplash.com/photo-1512290900672-1f02307374b7?q=80&w=800&auto=format&fit=crop',
    description: 'Gentle forehead line clearing for a neat hairline frame.',
  },
  {
    id: 'bc-4',
    category: 'BEAUTY',
    subcategory: 'Threading',
    name: 'Upper Lip',
    price: 70,
    starred: false,
    image: 'https://images.unsplash.com/photo-1512290900672-1f02307374b7?q=80&w=800&auto=format&fit=crop',
    description: 'Quick, sanitary upper lip threading with soothing aloe touch.',
  },
  {
    id: 'bc-5',
    category: 'BEAUTY',
    subcategory: 'Threading',
    name: 'Chin',
    price: 70,
    starred: false,
    image: 'https://images.unsplash.com/photo-1512290900672-1f02307374b7?q=80&w=800&auto=format&fit=crop',
    description: 'Targeted chin hair removal for a soft, refined contour.',
  },
  {
    id: 'bc-6',
    category: 'BEAUTY',
    subcategory: 'Threading',
    name: 'Full Face',
    price: 400,
    starred: false,
    image: 'https://images.unsplash.com/photo-1512290900672-1f02307374b7?q=80&w=800&auto=format&fit=crop',
    description: 'Comprehensive full face hair clearing including cheeks, jawline, and forehead.',
  },

  // ================= SKIN CARE =================
  {
    id: 'sc-1',
    category: 'SKIN',
    subcategory: 'Facial & Skin Care',
    name: 'Clean Up',
    price: 1000,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'Essential skin cleanup with deep pore steaming, extraction, scrub, and soothing pack.',
  },
  {
    id: 'sc-2',
    category: 'SKIN',
    subcategory: 'Facial & Skin Care',
    name: 'Glow Vita',
    price: 1600,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'Vital vitamin booster facial bringing instant natural luminosity to fatigued skin.',
  },
  {
    id: 'sc-3',
    category: 'SKIN',
    subcategory: 'Facial & Skin Care',
    name: 'Instant Glow Facial',
    price: 1700,
    starred: false,
    image: 'https://images.unsplash.com/photo-1512290900672-1f02307374b7?q=80&w=800&auto=format&fit=crop',
    description: 'Fast-action radiance facial ideal before evening events and special celebrations.',
  },
  {
    id: 'sc-4',
    category: 'SKIN',
    subcategory: 'Facial & Skin Care',
    name: 'Sensitive Skin Facial',
    price: 1800,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'Calming botanical formula designed to reduce redness and strengthen fragile skin barrier.',
  },
  {
    id: 'sc-5',
    category: 'SKIN',
    subcategory: 'Facial & Skin Care',
    name: 'Ultra Facial',
    price: 1800,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'Multi-action facial delivering 24-hour hydration, fine line smoothing, and tone clarity.',
  },
  {
    id: 'sc-6',
    category: 'SKIN',
    subcategory: 'Facial & Skin Care',
    name: 'Ten Clear Facial',
    price: 1900,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'Specialized tan removal formulation evening out stubborn sun exposure and dullness.',
  },
  {
    id: 'sc-7',
    category: 'SKIN',
    subcategory: 'Facial & Skin Care',
    name: 'O3+ Cleanup',
    price: 2000,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'Premium O3+ medical-grade salon cleanup for congested pores and hyperpigmentation.',
  },
  {
    id: 'sc-8',
    category: 'SKIN',
    subcategory: 'Facial & Skin Care',
    name: 'Oil Control Facial',
    price: 2200,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'Mattifying clarifying ritual balancing excess sebum and shrinking enlarged pores.',
  },
  {
    id: 'sc-9',
    category: 'SKIN',
    subcategory: 'Facial & Skin Care',
    name: 'Acne Facial',
    price: 2500,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'Antibacterial deep clearing therapy specifically calming active breakouts and scars.',
  },
  {
    id: 'sc-10',
    category: 'SKIN',
    subcategory: 'Facial & Skin Care',
    name: 'Anti Ageging Facial',
    price: 2500,
    starred: false,
    image: 'https://images.unsplash.com/photo-1512290900672-1f02307374b7?q=80&w=800&auto=format&fit=crop',
    description: 'Firming collagen boost facial reducing signs of aging, wrinkles, and saggy skin.',
  },
  {
    id: 'sc-11',
    category: 'SKIN',
    subcategory: 'Facial & Skin Care',
    name: 'Vitamin C Facial',
    price: 2700,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'High-potency antioxidant Vitamin C infusion fighting pigmentation and oxidative dullness.',
  },
  {
    id: 'sc-12',
    category: 'SKIN',
    subcategory: 'Facial & Skin Care',
    name: 'O3+ Facial',
    price: 2800,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'Full luxury O3+ whitening and glow protocol with brightening peel-off rubber mask.',
  },
  {
    id: 'sc-13',
    category: 'SKIN',
    subcategory: 'Facial & Skin Care',
    name: 'Tightening Facial',
    price: 2800,
    starred: false,
    image: 'https://images.unsplash.com/photo-1512290900672-1f02307374b7?q=80&w=800&auto=format&fit=crop',
    description: 'Targeted skin tightening and contour lift therapy with lifting lymph drainage.',
  },
  {
    id: 'sc-14',
    category: 'SKIN',
    subcategory: 'Facial & Skin Care',
    name: 'Advance Facial',
    price: 3000,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'Customized multi-step clinical grade treatment tailored to individual skin typology.',
  },
  {
    id: 'sc-15',
    category: 'SKIN',
    subcategory: 'Facial & Skin Care',
    name: 'Bridal Facial',
    price: 3500,
    starred: false,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop',
    description: 'Royal bridal radiance ritual giving immaculate translucent glow and velvety finish.',
  },
  {
    id: 'sc-16',
    category: 'SKIN',
    subcategory: 'Facial & Skin Care',
    name: 'Hydra Facial',
    price: 4700,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'Advanced vacuum vortex extraction, deep hyaluronic plumping, and oxygen infusion.',
  },
  {
    id: 'sc-17',
    category: 'SKIN',
    subcategory: 'Facial & Skin Care',
    name: 'Kenpaki Facial',
    price: 6000,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'Ultra-exclusive luxury elixir treatment for unmatched epidermal rejuvenation.',
  },

  // ================= ADDITIONAL SKIN CARE =================
  {
    id: 'asc-1',
    category: 'SKIN',
    subcategory: 'Additional Skin Care',
    name: 'Nature Facial With D-TEN',
    price: 1300,
    starred: false,
    image: 'https://images.unsplash.com/photo-1512290900672-1f02307374b7?q=80&w=800&auto=format&fit=crop',
    description: 'Organic natural botanical extract facial combined with deep de-tan action.',
  },
  {
    id: 'asc-2',
    category: 'SKIN',
    subcategory: 'Additional Skin Care',
    name: 'Gold Facial With D-TEN',
    price: 1500,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'Pure 24K gold dust polish combined with active de-tan brightening treatment.',
  },
  {
    id: 'asc-3',
    category: 'SKIN',
    subcategory: 'Additional Skin Care',
    name: 'Mix Fruit Facial',
    price: 2700,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'Enzyme rich natural fruit AHAs gently sloughing off dead cells for dewy glow.',
  },
  {
    id: 'asc-4',
    category: 'SKIN',
    subcategory: 'Additional Skin Care',
    name: 'Anti Aging Facial',
    price: 3000,
    starred: false,
    image: 'https://images.unsplash.com/photo-1512290900672-1f02307374b7?q=80&w=800&auto=format&fit=crop',
    description: 'Concentrated peptide and retinoid alternative therapy rejuvenating skin elasticity.',
  },
  {
    id: 'asc-5',
    category: 'SKIN',
    subcategory: 'Additional Skin Care',
    name: 'Chocolate Facial',
    price: 3500,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'Decadent cocoa antioxidants deeply hydrating and infusing a soft, supple texture.',
  },
  {
    id: 'asc-6',
    category: 'SKIN',
    subcategory: 'Additional Skin Care',
    name: 'Shahnaz Husain Facial',
    price: 3600,
    starred: false,
    image: 'https://images.unsplash.com/photo-1512290900672-1f02307374b7?q=80&w=800&auto=format&fit=crop',
    description: 'Iconic herbal Ayurvedic therapy formulated with precious plant botanicals.',
  },
  {
    id: 'asc-7',
    category: 'SKIN',
    subcategory: 'Additional Skin Care',
    name: 'Seasoul Facial',
    price: 4000,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'Dead Sea mineral mud and bio-marine extracts detoxifying and mineralizing dull skin.',
  },
  {
    id: 'asc-8',
    category: 'SKIN',
    subcategory: 'Additional Skin Care',
    name: 'Korean Glass Facial',
    price: 5500,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'Viral multi-step Korean beauty protocol providing poreless, luminous translucent glass skin.',
  },

  // ================= BODY CARE =================
  {
    id: 'bod-1',
    category: 'BODY',
    subcategory: 'Spa & Relaxing',
    name: 'Hair Spa',
    price: 1500,
    starred: true,
    image: 'https://images.unsplash.com/photo-1582095133179-bfd08e2fc6b3?q=80&w=800&auto=format&fit=crop',
    description: 'Deep conditioning steam spa, scalp pressure points, and restorative hair mask.',
  },
  {
    id: 'bod-2',
    category: 'BODY',
    subcategory: 'Spa & Relaxing',
    name: 'Dandruff Treatment',
    price: 800,
    starred: true,
    image: 'https://images.unsplash.com/photo-1582095133179-bfd08e2fc6b3?q=80&w=800&auto=format&fit=crop',
    description: 'Therapeutic antifungal scalp treatment relieving flaking and itchiness.',
  },
  {
    id: 'bod-3',
    category: 'BODY',
    subcategory: 'Body Care',
    name: 'Body Polishing',
    price: 2000,
    starred: true,
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=800&auto=format&fit=crop',
    description: 'Whole body micro-exfoliation and rich moisturizing glaze leaving skin satiny smooth.',
  },
  {
    id: 'bod-4',
    category: 'BODY',
    subcategory: 'Body Care',
    name: 'Full Body Massage',
    price: 2000,
    starred: true,
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=800&auto=format&fit=crop',
    description: 'Therapeutic Swedish & Ayurvedic oil massage dissolving muscular knots and fatigue.',
  },
  {
    id: 'bod-5',
    category: 'BODY',
    subcategory: 'Body Care',
    name: 'Face Bleach',
    price: 450,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'Gentle facial hair lightening to brighten and even out skin tones.',
  },
  {
    id: 'bod-6',
    category: 'BODY',
    subcategory: 'Body Care',
    name: 'Neck Bleach',
    price: 500,
    starred: false,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    description: 'Targeted neck bleach treatment matching tone seamlessly with the face.',
  },
  {
    id: 'bod-7',
    category: 'BODY',
    subcategory: 'Body Care',
    name: 'Head Massage (Male)',
    price: 400,
    starred: false,
    image: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?q=80&w=800&auto=format&fit=crop',
    description: 'Relaxing warm herbal oil head massage relieving mental tension and boosting blood circulation.',
  },
  {
    id: 'bod-8',
    category: 'BODY',
    subcategory: 'Body Care',
    name: 'Head Massage (Female)',
    price: 500,
    starred: false,
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=800&auto=format&fit=crop',
    description: 'Soothing warm almond/olive oil champi massage with deep neck and shoulder release.',
  },
  {
    id: 'bod-9',
    category: 'BODY',
    subcategory: 'Body Care',
    name: 'Foot Massage',
    price: 650,
    starred: true,
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=800&auto=format&fit=crop',
    description: 'Reflexology pressure points on tired feet relieving leg tension and fatigue.',
  },

  // ================= WAXING CARE =================
  {
    id: 'wax-1',
    category: 'WAXING',
    subcategory: 'Waxing Care',
    name: 'Full Arm',
    price: 400,
    starred: false,
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=800&auto=format&fit=crop',
    description: 'Complete arm waxing with hygienic strip formula and soothing aloe finish.',
  },
  {
    id: 'wax-2',
    category: 'WAXING',
    subcategory: 'Waxing Care',
    name: 'Full Legs',
    price: 800,
    starred: false,
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=800&auto=format&fit=crop',
    description: 'Thorough full leg hair removal for long-lasting silken smoothness.',
  },
  {
    id: 'wax-3',
    category: 'WAXING',
    subcategory: 'Waxing Care',
    name: 'Half Legs',
    price: 550,
    starred: false,
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=800&auto=format&fit=crop',
    description: 'Knee-to-ankle or thigh hair removal tailored to your preference.',
  },
  {
    id: 'wax-4',
    category: 'WAXING',
    subcategory: 'Waxing Care',
    name: 'Under Arms',
    price: 150,
    starred: false,
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=800&auto=format&fit=crop',
    description: 'Quick, sanitary underarm waxing with anti-bump astringent lotion.',
  },
  {
    id: 'wax-5',
    category: 'WAXING',
    subcategory: 'Waxing Care',
    name: 'Full Body',
    price: 3000,
    starred: false,
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=800&auto=format&fit=crop',
    description: 'Total body waxing service performed with premium gentle waxes.',
  },
  {
    id: 'wax-6',
    category: 'WAXING',
    subcategory: 'Waxing Care',
    name: 'Bikini',
    price: 1400,
    starred: false,
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=800&auto=format&fit=crop',
    description: 'Discreet, hygienic intimate waxing with specialized peelable wax.',
  },
  {
    id: 'wax-7',
    category: 'WAXING',
    subcategory: 'Waxing Care',
    name: 'Upper Lip',
    price: 60,
    starred: false,
    image: 'https://images.unsplash.com/photo-1512290900672-1f02307374b7?q=80&w=800&auto=format&fit=crop',
    description: 'Fast, clean upper lip wax for fine hair removal.',
  },
  {
    id: 'wax-8',
    category: 'WAXING',
    subcategory: 'Waxing Care',
    name: 'Full Face',
    price: 350,
    starred: false,
    image: 'https://images.unsplash.com/photo-1512290900672-1f02307374b7?q=80&w=800&auto=format&fit=crop',
    description: 'Complete gentle facial waxing for flawless makeup application.',
  },

  // ================= MANICURE =================
  {
    id: 'man-1',
    category: 'MANICURE & PEDICURE',
    subcategory: 'Manicure',
    name: 'Express',
    price: 500,
    starred: true,
    image: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?q=80&w=800&auto=format&fit=crop',
    description: 'Essential nail shaping, cuticle push, buffing, and quick polish.',
  },
  {
    id: 'man-2',
    category: 'MANICURE & PEDICURE',
    subcategory: 'Manicure',
    name: 'Regular',
    price: 700,
    starred: true,
    image: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?q=80&w=800&auto=format&fit=crop',
    description: 'Hand soak, exfoliation scrub, cuticle trimming, and relaxing hand massage.',
  },
  {
    id: 'man-3',
    category: 'MANICURE & PEDICURE',
    subcategory: 'Manicure',
    name: 'Lotus',
    price: 1500,
    starred: true,
    image: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?q=80&w=800&auto=format&fit=crop',
    description: 'Luxurious Lotus herbal botanicals restoring softness and youthful skin.',
  },
  {
    id: 'man-4',
    category: 'MANICURE & PEDICURE',
    subcategory: 'Manicure',
    name: 'Ultra Bright',
    price: 1200,
    starred: true,
    image: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?q=80&w=800&auto=format&fit=crop',
    description: 'Skin lightening and anti-tanning treatment revealing luminous hand complexion.',
  },
  {
    id: 'man-5',
    category: 'MANICURE & PEDICURE',
    subcategory: 'Manicure',
    name: 'D-TEN Bright',
    price: 1500,
    starred: true,
    image: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?q=80&w=800&auto=format&fit=crop',
    description: 'Intensive sun de-tanning therapy restoring clear, even hand tone.',
  },
  {
    id: 'man-6',
    category: 'MANICURE & PEDICURE',
    subcategory: 'Manicure',
    name: 'Bridal',
    price: 1800,
    starred: true,
    image: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?q=80&w=800&auto=format&fit=crop',
    description: 'Grand bridal hand spa ritual with gold scrub, nourishing wrap, and photo-ready shine.',
  },
  {
    id: 'man-7',
    category: 'MANICURE & PEDICURE',
    subcategory: 'Manicure',
    name: 'Aqua Manicure',
    price: 2200,
    starred: true,
    image: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?q=80&w=800&auto=format&fit=crop',
    description: 'Deep ocean aquatic hydration bath with marine collagen and cooling gel wrap.',
  },
  {
    id: 'man-8',
    category: 'MANICURE & PEDICURE',
    subcategory: 'Manicure',
    name: 'Seasoul Manicure',
    price: 2000,
    starred: true,
    image: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?q=80&w=800&auto=format&fit=crop',
    description: 'Dead Sea mineral salt soak and rich essential oil acupressure therapy.',
  },
  {
    id: 'man-9',
    category: 'MANICURE & PEDICURE',
    subcategory: 'Manicure',
    name: 'Kartin',
    price: 1300,
    starred: true,
    image: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?q=80&w=800&auto=format&fit=crop',
    description: 'Keratin fortified glove treatment strengthening brittle nails and repairing skin.',
  },

  // ================= PEDICURE =================
  {
    id: 'ped-1',
    category: 'MANICURE & PEDICURE',
    subcategory: 'Pedicure',
    name: 'Express',
    price: 700,
    starred: true,
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=800&auto=format&fit=crop',
    description: 'Fast foot cleanse, nail clipping, filing, and smoothing buff.',
  },
  {
    id: 'ped-2',
    category: 'MANICURE & PEDICURE',
    subcategory: 'Pedicure',
    name: 'Regular',
    price: 1000,
    starred: true,
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=800&auto=format&fit=crop',
    description: 'Warm foot jacuzzi bath, pumice callus removal, scrub, and massage.',
  },
  {
    id: 'ped-3',
    category: 'MANICURE & PEDICURE',
    subcategory: 'Pedicure',
    name: 'Lotus',
    price: 2000,
    starred: true,
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=800&auto=format&fit=crop',
    description: 'Herbal lotus foot soak melting stress and hydrating cracked heels.',
  },
  {
    id: 'ped-4',
    category: 'MANICURE & PEDICURE',
    subcategory: 'Pedicure',
    name: 'Ultra Bright',
    price: 1300,
    starred: true,
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=800&auto=format&fit=crop',
    description: 'Feet lightening and brightening treatment removing heavy sun marks.',
  },
  {
    id: 'ped-5',
    category: 'MANICURE & PEDICURE',
    subcategory: 'Pedicure',
    name: 'D-TEN Bright',
    price: 1700,
    starred: true,
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=800&auto=format&fit=crop',
    description: 'Intensive foot and ankle de-tan pack restoring fresh clear skin tone.',
  },
  {
    id: 'ped-6',
    category: 'MANICURE & PEDICURE',
    subcategory: 'Pedicure',
    name: 'Kartin',
    price: 1700,
    starred: true,
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=800&auto=format&fit=crop',
    description: 'Keratin sock therapy deeply softening hardened heels and nourishing cuticles.',
  },
  {
    id: 'ped-7',
    category: 'MANICURE & PEDICURE',
    subcategory: 'Pedicure',
    name: 'Aqua Pedicure',
    price: 2700,
    starred: true,
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=800&auto=format&fit=crop',
    description: 'Hydro-revitalizing marine foot bath, cooling algae peel, and circulation booster.',
  },
  {
    id: 'ped-8',
    category: 'MANICURE & PEDICURE',
    subcategory: 'Pedicure',
    name: 'Seasoul Pedicure',
    price: 2500,
    starred: true,
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=800&auto=format&fit=crop',
    description: 'Dead Sea mineral crystal scrub with deeply soothing warm towel compression.',
  },

  // ================= MAKEUP =================
  {
    id: 'mu-p-1',
    category: 'MAKEUP',
    subcategory: 'Party Makeup',
    name: 'Normal',
    price: 3500,
    starred: false,
    image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=800&auto=format&fit=crop',
    description: 'Clean, elegant party makeup enhancing your natural features beautifully.',
  },
  {
    id: 'mu-p-2',
    category: 'MAKEUP',
    subcategory: 'Party Makeup',
    name: 'HD',
    price: 4500,
    starred: false,
    image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=800&auto=format&fit=crop',
    description: 'High-definition camera-ready finish with long-wearing air-weight foundation.',
  },
  {
    id: 'mu-p-3',
    category: 'MAKEUP',
    subcategory: 'Party Makeup',
    name: 'Celebrity',
    price: 5500,
    starred: false,
    image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=800&auto=format&fit=crop',
    description: 'Red carpet luxury makeup with dramatic eye artistry, lashes, and sculpted glow.',
  },

  {
    id: 'mu-e-1',
    category: 'MAKEUP',
    subcategory: 'Engagement Makeup',
    name: 'Normal',
    price: 4000,
    starred: false,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop',
    description: 'Graceful engagement ceremony makeup tailored to your jewelry and outfit palette.',
  },
  {
    id: 'mu-e-2',
    category: 'MAKEUP',
    subcategory: 'Engagement Makeup',
    name: 'HD',
    price: 5500,
    starred: false,
    image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=800&auto=format&fit=crop',
    description: 'Flawless HD engagement makeup capturing radiant light across every photograph.',
  },
  {
    id: 'mu-e-3',
    category: 'MAKEUP',
    subcategory: 'Engagement Makeup',
    name: 'Celebrity',
    price: 7500,
    starred: false,
    image: 'https://images.unsplash.com/photo-1512290900672-1f02307374b7?q=80&w=800&auto=format&fit=crop',
    description: 'Signature celebrity contouring, premium mink lashes, and bespoke setting.',
  },

  // BRIDAL MAKEUP (Keep Bridal Celebrity as ₹1,300 exactly as explicitly instructed!)
  {
    id: 'mu-b-1',
    category: 'MAKEUP',
    subcategory: 'Bridal Makeup',
    name: 'Normal',
    price: 5500,
    starred: false,
    image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=800&auto=format&fit=crop',
    description: 'Classic Indian bridal makeup highlighting traditional royalty and long wear.',
  },
  {
    id: 'mu-b-2',
    category: 'MAKEUP',
    subcategory: 'Bridal Makeup',
    name: 'HD',
    price: 8500,
    starred: false,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop',
    description: 'Ultra-HD waterproof, smudge-proof bridal masterwork tailored for wedding cameras.',
  },
  {
    id: 'mu-b-3',
    category: 'MAKEUP',
    subcategory: 'Bridal Makeup',
    name: 'Celebrity',
    price: 1300,
    starred: false,
    image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=800&auto=format&fit=crop',
    description: 'Celebrity bridal glam service preserved exactly as supplied at special salon pricing.',
  },

  {
    id: 'mu-r-1',
    category: 'MAKEUP',
    subcategory: 'Reception Makeup',
    name: 'Normal',
    price: 6000,
    starred: false,
    image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=800&auto=format&fit=crop',
    description: 'Modern reception glam bringing elevated evening elegance and flawless wear.',
  },
  {
    id: 'mu-r-2',
    category: 'MAKEUP',
    subcategory: 'Reception Makeup',
    name: 'HD',
    price: 7500,
    starred: false,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop',
    description: 'HD reception makeup featuring high-beam luminous cheekbones and sculpted brows.',
  },
  {
    id: 'mu-r-3',
    category: 'MAKEUP',
    subcategory: 'Reception Makeup',
    name: 'Celebrity',
    price: 8500,
    starred: false,
    image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=800&auto=format&fit=crop',
    description: 'Couture celebrity finish designed for stage lighting, flash photography, and all-night wear.',
  },

  // HAIR STYLE
  {
    id: 'mu-hs-1',
    category: 'MAKEUP',
    subcategory: 'Hair Style',
    name: 'Open Hair Style',
    price: 1200,
    starred: true,
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=800&auto=format&fit=crop',
    description: 'Cascading waves, textured half-up styles, and soft pinned arrangements.',
  },
  {
    id: 'mu-hs-2',
    category: 'MAKEUP',
    subcategory: 'Hair Style',
    name: 'One Side Hairstyle',
    price: 800,
    starred: true,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop',
    description: 'Chic asymmetrical swept style with delicate accessory placement.',
  },
  {
    id: 'mu-hs-3',
    category: 'MAKEUP',
    subcategory: 'Hair Style',
    name: 'Advance Hairstyle',
    price: 1400,
    starred: true,
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?q=80&w=800&auto=format&fit=crop',
    description: 'Architectural bridal buns, intricate braided crowns, and floral setting.',
  },
  {
    id: 'mu-hs-4',
    category: 'MAKEUP',
    subcategory: 'Hair Style',
    name: 'Messy Look Hair Style',
    price: 800,
    starred: true,
    image: 'https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?q=80&w=800&auto=format&fit=crop',
    description: 'Boho romantic textured messy bun or loose effortless braids.',
  },
];

// ================= EXACT D-TEN COMPARISON DATA =================
export const dTenDataMale: DTenItem[] = [
  { area: 'Face', gender: 'MALE', regularPrice: 400, premiumPrice: 500 },
  { area: 'Neck', gender: 'MALE', regularPrice: 350, premiumPrice: 500 },
  { area: 'Full Arms', gender: 'MALE', regularPrice: 650, premiumPrice: 800 },
  { area: 'Half Legs', gender: 'MALE', regularPrice: 600, premiumPrice: 800 },
];

export const dTenDataFemale: DTenItem[] = [
  { area: 'Face', gender: 'FEMALE', regularPrice: 400, premiumPrice: 600 },
  { area: 'Neck', gender: 'FEMALE', regularPrice: 350, premiumPrice: 500 },
  { area: 'Full Arms', gender: 'FEMALE', regularPrice: 650, premiumPrice: 800 },
  { area: 'Half Legs', gender: 'FEMALE', regularPrice: 600, premiumPrice: 800 },
];
